main: com.ollicafe.dominationarcana.DominationArcana
name: DominationArcana
version: 0.1
author: olli
website: ollicafe.com
description: Fall before absolute power
api-version: 1.16

commands:
  ash:
    description: Return to Ash
    usage: /ash